config/routes.rb
Mancala::Application.routes.draw do
  resources :boards
  get "/move" => "boards#move", :as => "move"

  resources :cups

  resources :players

  

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :players
  has_many :cups
end

app/models/cup.rb
class Cup < ActiveRecord::Base
  attr_accessible :marbles, :board_id
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])
    @cups = Cup.where(board_id: @board)
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        14.times do
          cup = Cup.create(marbles: 4, board_id: @board.id)
          if(cup.id % 7 == 0)
            cup.marbles = 0
            cup.save
          end
        end
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end

  def move
    @board = Board.find(params[:board_id])

    @cup = Cup.find(params[:cup_id])
    @marble = @cup.marbles
    @cup.marbles = 0
    @cup.save
    cup_id = @cup.id
    while @marble > 0 do
      if cup_id == 14
        cup_id = 1
      else
        cup_id += 1
      end
      cup = Cup.find(cup_id)
      cup.marbles += 1
      @marble -= 1
      cup.save
    end
    redirect_to @board
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params[:board]
    end

end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
  before_action :set_cup, only: [:show, :edit, :update, :destroy]

  # GET /cups
  # GET /cups.json
  def index
    @cups = Cup.all
  end

  # GET /cups/1
  # GET /cups/1.json
  def show
  end

  # GET /cups/new
  def new
    @cup = Cup.new
  end

  # GET /cups/1/edit
  def edit
  end

  # POST /cups
  # POST /cups.json
  def create
    @cup = Cup.new(cup_params)

    respond_to do |format|
      if @cup.save
        format.html { redirect_to @cup, notice: 'Cup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cup }
      else
        format.html { render action: 'new' }
        format.json { render json: @cup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cups/1
  # PATCH/PUT /cups/1.json
  def update
    respond_to do |format|
      if @cup.update(cup_params)
        format.html { redirect_to @cup, notice: 'Cup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cups/1
  # DELETE /cups/1.json
  def destroy
    @cup.destroy
    respond_to do |format|
      format.html { redirect_to cups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cup
      @cup = Cup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cup_params
      params.require(:cup).permit(:marbles)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cups_helper.rb
module CupsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Cups:</strong>
  <hr>
  <br>
  <% @cups.each do |cup| %>
    <%= cup.id %>
    |
    <%= cup.marbles %>
    <% if cup.id % 7 != 0 %>
      <%= link_to 'Move', move_path(cup_id: cup.id, board_id: @board.id) %>
    <% end %>
    <hr>
  <% end %>
</p>

<%= link_to 'Edit', edit_board_path(@cup) %> |
<%= link_to 'Back', boards_path %>

app/views/boards/show.html.haml
.board
  %h1 Board!!!!!!!!!!!1
  =@cups

=link_to 'Edit' edit_board_path(@board)
=link_to 'Back' boards_path

app/views/cups/_form.html.erb
<%= form_for(@cup) do |f| %>
  <% if @cup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cup.errors.count, "error") %> prohibited this cup from being saved:</h2>

      <ul>
      <% @cup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marbles %><br>
    <%= f.number_field :marbles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cups/edit.html.erb
<h1>Editing cup</h1>

<%= render 'form' %>

<%= link_to 'Show', @cup %> |
<%= link_to 'Back', cups_path %>

app/views/cups/index.html.erb
<h1>Listing cups</h1>

<table>
  <thead>
    <tr>
      <th>Marbles</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cups.each do |cup| %>
      <tr>
        <td><%= cup.marbles %></td>
        <td><%= link_to 'Show', cup %></td>
        <td><%= link_to 'Edit', edit_cup_path(cup) %></td>
        <td><%= link_to 'Destroy', cup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cup', new_cup_path %>

app/views/cups/new.html.erb
<h1>New cup</h1>

<%= render 'form' %>

<%= link_to 'Back', cups_path %>

app/views/cups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marbles:</strong>
  <%= @cup.marbles %>
</p>

<%= link_to 'Edit', edit_cup_path(@cup) %> |
<%= link_to 'Back', cups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mancala</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>